# Generated by Django 5.1.5 on 2025-02-15 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waitlists', '0002_waitlistentry_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waitlistentry',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
